version: '3.8'

services:

  authenticationDB:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authentication
    volumes:
      - auth_data:/var/lib/mysql
    networks:
      - auth_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure

  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    depends_on:
      authenticationDB:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://root:root@authenticationDB/authentication
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "5000:5000"
    networks:
      - auth_network
    restart: on-failure


  storeDB:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
    volumes:
      - store_data:/var/lib/mysql
    networks:
      - store_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure

  ganache:
    image: trufflesuite/ganache-cli
    command: --accounts 10 --networkId 5777 --gasPrice 1 --deterministic --host 0.0.0.0
    ports:
      - "8545:8545"
    networks:
      - store_network
    restart: on-failure

  owner:
    build:
      context: .
      dockerfile: applications/owner/Dockerfile
    depends_on:
      storeDB:
        condition: service_healthy
      ganache:
        condition: service_started
    environment:
      DATABASE_URL: mysql+pymysql://root:root@storeDB/store
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      BLOCKCHAIN_URL: http://ganache:8545
      OWNER_PRIVATE_KEY: ${OWNER_PRIVATE_KEY}
    ports:
      - "5001:5000"
    networks:
      - store_network
    restart: on-failure

  customer:
    build:
      context: .
      dockerfile: applications/customer/Dockerfile
    depends_on:
      storeDB:
        condition: service_healthy
      ganache:
        condition: service_started
    environment:
      DATABASE_URL: mysql+pymysql://root:root@storeDB/store
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      BLOCKCHAIN_URL: http://ganache:8545
      OWNER_PRIVATE_KEY: ${OWNER_PRIVATE_KEY}
    ports:
      - "5002:5000"
    networks:
      - store_network
    restart: on-failure

  courier:
    build:
      context: .
      dockerfile: applications/courier/Dockerfile
    depends_on:
      storeDB:
        condition: service_healthy
      ganache:
        condition: service_started
    environment:
      DATABASE_URL: mysql+pymysql://root:root@storeDB/store
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      BLOCKCHAIN_URL: http://ganache:8545
      OWNER_PRIVATE_KEY: ${OWNER_PRIVATE_KEY}
    ports:
      - "5003:5000"
    networks:
      - store_network
    restart: on-failure

  tests:
    build:
      context: ./Tests
      dockerfile: Dockerfile
    depends_on:
      authenticationDB:
        condition: service_healthy
      storeDB:
        condition: service_healthy
      authentication:
        condition: service_started
      owner:
        condition: service_started
      customer:
        condition: service_started
      courier:
        condition: service_started
    networks:
      - auth_network
      - store_network
    command: >
      sh -c "python reset_databases.py && python main.py --type all
      --with-authentication
      --authentication-url http://authentication:5000
      --jwt-secret JWT_SECRET_DEV_KEY
      --roles-field roles
      --owner-role owner
      --customer-role customer
      --courier-role courier
      --owner-url http://owner:5000
      --customer-url http://customer:5000
      --courier-url http://courier:5000
      --with-blockchain
      --provider-url http://ganache:8545
      --owner-private-key 0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d"
    profiles:
      - test


networks:
  auth_network:
    driver: bridge
  store_network:
    driver: bridge


volumes:
  auth_data:
  store_data:
